sudo: required
services:
  - docker

before_install:
  - docker build -t oke/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run oke/react-test npm test -- --coverage

after_success:
  - docker build -t oke/multi-client ./client
  - docker build -t oke/multi-nginx ./nginx
  - docker build -t oke/multi-server ./server  
  - docker build -t oke/multi-worker ./worker
  # Ingresar a docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tomar las imagenes y hacer push a docker hub
  - docker push oke/multi-client ./client
  - docker push oke/multi-nginx ./nginx
  - docker push oke/multi-server ./server  
  - docker push oke/multi-worker ./worker
