sudo: required
services:
  - docker

before_install:
  - docker build -t oke123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run oke123/react-test npm test -- --coverage

after_success:
  - docker build -t oke123/multi-client ./client
  - docker build -t oke123/multi-nginx ./nginx
  - docker build -t oke123/multi-server ./server  
  - docker build -t oke123/multi-worker ./worker
  # Ingresar a docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tomar las imagenes y hacer push a docker hub
  - docker push oke123/multi-client
  - docker push oke123/multi-nginx 
  - docker push oke123/multi-server
  - docker push oke123/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-289548232838
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY